Repository ouzi-dev/avro-kedavro, pull requests merged in 2020-04, with the labels that each got.

#21 fix: update dependencies to latest
  Makefile
  go.mod
  go.sum
  package-lock.json
  package.json
Labels: approved, lgtm, size/XXL

#22 fix: support float string as timestamp
  README.md
  package-lock.json
  package.json
  pkg/kedavro/conversion_test.go
  pkg/kedavro/primitiveparsers.go
  pkg/kedavro/schema.go
Labels: approved, lgtm, size/XL

#23 feat: added new option to initialise null timestamps to time.Now()
  README.md
  pkg/kedavro/conversion_test.go
  pkg/kedavro/parser.go
  pkg/kedavro/primitiveparsers.go
  pkg/types/types.go
Labels: approved, lgtm, size/L
